import axios from "axios";

const TOKEN =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiYXVkIjoiaHR0cDovLzIwLjI0NC41Ni4xNDQvZXZhbHVhdGlvbi1zZXJ2aWNlIiwiZW1haWwiOiJrcmlzaG5hOTUwMjIwMjQ5MUBnbWFpbC5jb20iLCJleHAiOjE3NTM2ODI4NTAsImlhdCI6MTc1MzY4MTk1MCwiaXNzIjoiQWZmb3JkIE1lZGljYWwgVGVjaG5vbG9naWVzIFByaXZhdGUgTGltaXRlZCIsImp0aSI6IjBkY2I0ZGJlLWQ1ZDAtNDQwNi05OTNhLTJiZTM2ZDM3ZmNmMiIsImxvY2FsZSI6ImVuLUlOIiwibmFtZSI6ImpheWFrcmlzaG5hIiwic3ViIjoiNDQ5Zjc5ZmItMzljYS00ZWVhLWJiZGQtYTExZWJmYjBlNTU1In0sImVtYWlsIjoia3Jpc2huYTk1MDIyMDI0OTFAZ21haWwuY29tIiwibmFtZSI6ImpheWFrcmlzaG5hIiwicm9sbE5vIjoiMjI4ODFhMDVoNiIsImFjY2Vzc0NvZGUiOiJ3UEVmR1oiLCJjbGllbnRJRCI6IjQ0OWY3OWZiLTM5Y2EtNGVlYS1iYmRkLWExMWViZmIwZTU1NSIsImNsaWVudFNlY3JldCI6Ik53Q1RWVmpDQlh6TmVHZ04ifQ.ir5hWIRKKRberj7an4KP3JrtjcF7C5gdoPN1bp0pAeI";
const TEST_SERVER_API = "http://20.244.56.144/evaluation-service/logs";

async function Logger(req) {
  console.log(req.body);
  const response = await axios.post(TEST_SERVER_API, req.body, {
    headers: { Authorization: `Bearer ${TOKEN}` },
  });
  res.json(response.data);
}

export default Logger;
